/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PathologistRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PathologistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.PortalAdminRole.DonorStatusJPanel;

/**
 *
 * @author raunak
 */
public class PathologistWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private PathologistOrganization labOrganization;
    private Network network;
    private Enterprise enterprise;
    
    private DB4OUtil  dB4OUtil = DB4OUtil.getInstance();
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public PathologistWorkAreaPanel( JPanel userProcessContainer,UserAccount account, PathologistOrganization organization,Enterprise enterprise, EcoSystem business,Network network) {
        initComponents();
        
       // this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (PathologistOrganization)organization;
        this.network=network;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        
       
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 119, 119));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageRequest.setBackground(new java.awt.Color(0, 204, 204));
        btnManageRequest.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        btnManageRequest.setForeground(new java.awt.Color(102, 0, 0));
        btnManageRequest.setText("Manage Request");
        btnManageRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestActionPerformed(evt);
            }
        });
        add(btnManageRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 200, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kefa", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Pathologist Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 430, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/namita/Desktop/Images for AED Project/101.jpeg.jpeg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 360, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestActionPerformed

        PathologistWorkRequestJPanel panel = new PathologistWorkRequestJPanel(userProcessContainer,business,userAccount,labOrganization,enterprise, network);
        userProcessContainer.add("PathologistWorkRequestJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageRequestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
